<a href="https://colab.research.google.com/github/Ayan02-coder/Computational_Satistics/blob/Miniproject/PCA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.decomposition import PCA

In [ ]:
from sklearn.datasets import load_linnerud

X,y = load_linnerud(return_X_y=True)

In [ ]:
df1=pd.DataFrame(X, columns=["Weight","Waist","Pules"])
print(df1)

    Weight  Waist  Pules
0      5.0  162.0   60.0
1      2.0  110.0   60.0
2     12.0  101.0  101.0
3     12.0  105.0   37.0
4     13.0  155.0   58.0
5      4.0  101.0   42.0
6      8.0  101.0   38.0
7      6.0  125.0   40.0
8     15.0  200.0   40.0
9     17.0  251.0  250.0
10    17.0  120.0   38.0
11    13.0  210.0  115.0
12    14.0  215.0  105.0
13     1.0   50.0   50.0
14     6.0   70.0   31.0
15    12.0  210.0  120.0
16     4.0   60.0   25.0
17    11.0  230.0   80.0
18    15.0  225.0   73.0
19     2.0  110.0   43.0


In [ ]:
df2=pd.DataFrame(y, columns=["chins","sit_ups","jumps"])
print(df2)

    chins  sit_ups  jumps
0   191.0     36.0   50.0
1   189.0     37.0   52.0
2   193.0     38.0   58.0
3   162.0     35.0   62.0
4   189.0     35.0   46.0
5   182.0     36.0   56.0
6   211.0     38.0   56.0
7   167.0     34.0   60.0
8   176.0     31.0   74.0
9   154.0     33.0   56.0
10  169.0     34.0   50.0
11  166.0     33.0   52.0
12  154.0     34.0   64.0
13  247.0     46.0   50.0
14  193.0     36.0   46.0
15  202.0     37.0   62.0
16  176.0     37.0   54.0
17  157.0     32.0   52.0
18  156.0     33.0   54.0
19  138.0     33.0   68.0


In [ ]:
df=pd.merge(df1,df2,left_index=True,right_index=True)
df

Weight  Waist  Pules  chins  sit_ups  jumps
0      5.0  162.0   60.0  191.0     36.0   50.0
1      2.0  110.0   60.0  189.0     37.0   52.0
2     12.0  101.0  101.0  193.0     38.0   58.0
3     12.0  105.0   37.0  162.0     35.0   62.0
4     13.0  155.0   58.0  189.0     35.0   46.0
5      4.0  101.0   42.0  182.0     36.0   56.0
6      8.0  101.0   38.0  211.0     38.0   56.0
7      6.0  125.0   40.0  167.0     34.0   60.0
8     15.0  200.0   40.0  176.0     31.0   74.0
9     17.0  251.0  250.0  154.0     33.0   56.0
10    17.0  120.0   38.0  169.0     34.0   50.0
11    13.0  210.0  115.0  166.0     33.0   52.0
12    14.0  215.0  105.0  154.0     34.0   64.0
13     1.0   50.0   50.0  247.0     46.0   50.0
14     6.0   70.0   31.0  193.0     36.0   46.0
15    12.0  210.0  120.0  202.0     37.0   62.0
16     4.0   60.0   25.0  176.0     37.0   54.0
17    11.0  230.0   80.0  157.0     32.0   52.0
18    15.0  225.0   73.0  156.0     33.0   54.0
19     2.0  110.0   43.0  138.0     33.0   68.0

In [ ]:
df.describe()

Weight       Waist      Pules       chins    sit_ups      jumps
count  20.000000   20.000000   20.00000   20.000000  20.000000  20.000000
mean    9.450000  145.550000   70.30000  178.600000  35.400000  56.100000
std     5.286278   62.566575   51.27747   24.690505   3.201973   7.210373
min     1.000000   50.000000   25.00000  138.000000  31.000000  46.000000
25%     4.750000  101.000000   39.50000  160.750000  33.000000  51.500000
50%    11.500000  122.500000   54.00000  176.000000  35.000000  55.000000
75%    13.250000  210.000000   85.25000  191.500000  37.000000  60.500000
max    17.000000  251.000000  250.00000  247.000000  46.000000  74.000000

In [ ]:
data = df[["chins","sit_ups","jumps"]]

In [ ]:
data

chins  sit_ups  jumps
0   191.0     36.0   50.0
1   189.0     37.0   52.0
2   193.0     38.0   58.0
3   162.0     35.0   62.0
4   189.0     35.0   46.0
5   182.0     36.0   56.0
6   211.0     38.0   56.0
7   167.0     34.0   60.0
8   176.0     31.0   74.0
9   154.0     33.0   56.0
10  169.0     34.0   50.0
11  166.0     33.0   52.0
12  154.0     34.0   64.0
13  247.0     46.0   50.0
14  193.0     36.0   46.0
15  202.0     37.0   62.0
16  176.0     37.0   54.0
17  157.0     32.0   52.0
18  156.0     33.0   54.0
19  138.0     33.0   68.0

In [ ]:
scaler = StandardScaler()
data_scaled = scaler.fit_transform(data)

In [ ]:
data_scaled

array([[ 0.51526412,  0.1922524 , -0.86798121],
       [ 0.43215701,  0.51267307, -0.5833972 ],
       [ 0.59837124,  0.83309374,  0.2703548 ],
       [-0.68978907, -0.12816827,  0.83952281],
       [ 0.43215701, -0.12816827, -1.43714921],
       [ 0.1412821 ,  0.1922524 , -0.0142292 ],
       [ 1.34633529,  0.83309374, -0.0142292 ],
       [-0.48202128, -0.44858894,  0.5549388 ],
       [-0.10803925, -1.40985094,  2.54702682],
       [-1.02221753, -0.7690096 , -0.0142292 ],
       [-0.39891416, -0.44858894, -0.86798121],
       [-0.52357483, -0.7690096 , -0.5833972 ],
       [-1.02221753, -0.44858894,  1.12410681],
       [ 2.84226339,  3.39645908, -0.86798121],
       [ 0.59837124,  0.1922524 , -1.43714921],
       [ 0.97235326,  0.51267307,  0.83952281],
       [-0.10803925,  0.51267307, -0.2988132 ],
       [-0.89755686, -1.08943027, -0.5833972 ],
       [-0.93911042, -0.7690096 , -0.2988132 ],
       [-1.68707447, -0.7690096 ,  1.69327481]])

In [ ]:
pca = PCA()
pca.fit(data_scaled)

PCA()

In [ ]:
print(pca.explained_variance_ratio_)

[0.70137682 0.25540925 0.04321393]


In [ ]:
data_transformed = pca.transform(data_scaled)

In [ ]:
data_transformed

array([[ 0.81780452, -0.58220197,  0.21928546],
       [ 0.8507056 , -0.24984705, -0.06182303],
       [ 0.80612641,  0.67090907, -0.15882779],
       [-0.87717135,  0.52589423, -0.38863903],
       [ 0.79689562, -1.22066043,  0.3788537 ],
       [ 0.22012086,  0.08614684, -0.03534988],
       [ 1.40657367,  0.6266703 ,  0.36837643],
       [-0.82982855,  0.22924815, -0.01906539],
       [-2.03812801,  1.85280993,  0.9485923 ],
       [-1.14496499, -0.54014271, -0.18386939],
       [-0.18141258, -1.03940481,  0.02197784],
       [-0.58602147, -0.91429091,  0.16281782],
       [-1.41552003,  0.59149341, -0.39524098],
       [ 4.36950026,  1.06105327, -0.38654923],
       [ 1.10926846, -1.07537962,  0.27108881],
       [ 0.60350901,  1.19735008,  0.33945951],
       [ 0.38399813, -0.14609356, -0.44158532],
       [-1.0321341 , -1.11908645,  0.12314078],
       [-0.97248506, -0.77482859, -0.12847932],
       [-2.28683639,  0.8203608 , -0.6341633 ]])